CAMBIO_ITEMS = {
    "RUÍDO": ["OK", "POSSUI"],
    "VAZAMENTO DE ÓLEO": ["OK", "POSSUI"],
    "COIFA RODA": ["OK", "LADO DIREITO", "LADO ESQUERDO"],
    "COIFA CÂMBIO": ["OK", "LADO DIREITO", "LADO ESQUERDO"],
    "NÍVEL ÓLEO": ["OK", "BAIXO"],
    "EMBREAGEM (DUREZA E CURSO)": ["OK", "MEDIANA", "RUIM"],
    "FOLGA TRAMBULADOR": ["OK", "RUIM"],
}
