FREIOS_ITEMS = {
    "FOLGA CAVALETE DE FREIO DIANTEIRO": ["OK", "RUIM"],
    "PASTILHA FREIO DIANTEIRO": ["VERDE", "AMARELO", "VERMELHO"],
    "DISCO DE FREIO DIANTEIRO": ["OK", "DESGASTADO"],
    "FOLGA CAVALETE DE FREIO TRASEIRO": ["OK", "RUIM"],
    "PASTILHA DE FREIO TRASEIRA": ["VERDE", "AMARELO", "VERMELHO", "NÃO POSSUI"],
    "DISCO DE FREIO TRASEIRO": ["OK", "DESGASTADO"],
    "LONA DE FREIO": ["OK", "DESGASTADO"],
    "TAMBOR DE FREIO": ["OK", "DESGASTADO"],
    "FLUÍDO DE FREIO": ["LIMPO", "SUJO", "MUITO SUJO"],
    "FREIO DE ESTACIONAMENTO": ["OK", "RUIM"],
    "ATUAÇÃO SERVO": ["OK", "RUIM"],
    "VAZAMENTO DE FLUÍDO": ["OK", "DD", "DE", "TD", "TE"],
    "LUZ DO ABS": ["OK", "RUIM"]
}
